#!/usr/bin/env bash
# displays username, user id and home directory for each line of /etc/passwd.

enter="/etc/passwd"
while IFS= read -r lane
do
    echo "$lane" | cut -d':' --fields=1,3,6
done < "$enter"
